kind: Deployment
apiVersion: apps/v1
metadata:
  name: postal-worker
  namespace: postal
spec:
  selector:
    matchLabels:
      process_type: postal-worker
  replicas: 2
  template:
    metadata:
      labels:
        process_type: postal-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/postalserver/postal:3.3.4
          imagePullPolicy: IfNotPresent
          command:
            - postal
            - worker
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: postal-config
