---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postal-mariadb
  namespace: postal
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 11.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 10.6.8-debian-10-r0
      pullPolicy: IfNotPresent

    primary:
      persistence:
        size: 20Gi

    secondary:
      replicaCount: 0

    auth:
      rootPassword: "${SECRET_POSTAL_MARIADB_PASS}"
      username: postal
      password: "${SECRET_POSTAL_MARIADB_PASS}"
      database: postal
