---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io
      chart: minio
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      size: 20Gi

    resources:
      requests:
        memory: 3Gi

    mode: standalone

    rootUser: "${SECRET_MINIO_USER}"
    rootPassword: "${SECRET_MINIO_PASS}"

    users:
      - accessKey: "${SECRET_MINIO_ACCESS_KEY}"
        secretKey: "${SECRET_MINIO_SECRET_KEY}"
        policy: readwrite

    ingress:
      enabled: true
      ingressClassName: "nginx"
      path: /
      hosts:
        - &s3domain s3.${SECRET_CLUSTER_DOMAIN}

      tls:
        - hosts:
            - *s3domain
          secretName: *s3domain

    consoleIngress:
      enabled: true
      ingressClassName: "nginx"
      path: /
      hosts:
        - &domain minio.${SECRET_CLUSTER_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production

      tls:
        - hosts:
            - *domain
          secretName: *domain
