---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rfspager
  namespace: production
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=http://charts.npratley.net
      chart: laravel
      version: 0.0.9
      sourceRef:
        kind: HelmRepository
        name: nicko170-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: docker.io/nick170/rfspager
      tag: v1.3.5

    imagePullSecrets:
      - name: regcred

    web:
      enabled: true
      count: 3
      command: /cnb/process/web

    cron:
      enabled: true
      command: /cnb/process/schedule
      schedule: "*/1 * * * *"

    worker:
      enabled: true
      count: 2
      command: /cnb/process/worker

    env:
      TZ: "Australia/Sydney"
      PORT: 8080

    envFrom:
      - configMapRef:
          name: rfspager-config
      - secretRef:
          name: rfspager-secrets

    volumes:
      - name: secret-files
        secret:
          secretName: rfspager-secret-files

    volumeMounts:
      - name: secret-files
        mountPath: /secrets/

    ingress:
      enabled: true
      ingressClassName: "nginx"

      hosts:
        - host: ${SECRET_CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: Prefix

      tls:
        - hosts:
            - ${SECRET_CLUSTER_DOMAIN}
          secretName: ${SECRET_CLUSTER_DOMAIN}

      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

    redis:
      enabled: true

    postgresql:
      enabled: true

      image:
        repository: bitnami/postgresql
        tag: 14.3.0
        pullPolicy: IfNotPresent

      global:
        postgresql:
          auth:
            postgresPassword: ${SECRET_RFSPAGER_DB_PASSWORD}
            username: rfspager
            password: ${SECRET_RFSPAGER_DB_PASSWORD}
            database: rfspager


      primary:
        containerSecurityContext:
          runAsUser: 0

        extraVolumes:
          - name: postgres-startup-scripts
            configMap:
              name: postgres-startup-scripts

        extraVolumeMounts:
          - name: postgres-startup-scripts
            mountPath: /docker-entrypoint-preinitdb.d/

        persistence:
          enabled: true
          size: 50Gi

      readReplicas:
        replicaCount: 0
