apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: rfspager-secrets
    namespace: production
stringData:
    APP_KEY: ENC[AES256_GCM,data:tyLXNX6G6ZhJUO9vWD3sY/EIuGh9vRbpZKhKngsQpcqExlIq4OU0Y9fMuzvZBDcZiGwU,iv:wSeUHw94kP6fpZ8qVtA/dv2nPfsOt2ClUL3vlfec1s0=,tag:U9KKtFu6/4/yIw6zQMRJIQ==,type:str]
    AWS_ENDPOINT: ENC[AES256_GCM,data:UmPmP3Ezc73HEz1uWGBbmesmnEdrYPXgA3mXmvCDGwE=,iv:pLD4PFcw3o5myxqyVzwl/00ZOhoYEQ+iiKC69Hq7cUI=,tag:eI9eq/kfL02HcTuwPNAPOg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/HkZCkCqL6ZlN1UsMDEZM4q1EqYCyNLe+ao=,iv:SFvPk5Q3UckOoYAy8GlO1BS21B+Gz9BXG50n+SutHsk=,tag:HWkxywLB1vdMDlKwdMDBKA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EoMvcKyaQVh8zPqVsajHhdb/eJekrXCjPeM=,iv:vYAsulibSa/IOeRji4Mnt9y6ut7r2OhYnhzsP4D9pes=,tag:HVXMKQD4LmUErS4zcDfPEw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:dbIFsggy1G/qcZPZ,iv:94QjO/TqNS8QEts4H3NDU+BryvRPYInRUawl9x9kkPc=,tag:VHdjcd7gOMAm63/4SuoPDA==,type:str]
    AWS_BUCKET: ENC[AES256_GCM,data:WwU3qlaALoU=,iv:lWisMfRVTvmg0t7/xW5p5NTpGGOCGE/iQceG5jQxNMo=,tag:/BDkBcxglSXvOOXLFHuqug==,type:str]
    AWS_USE_PATH_STYLE_ENDPOINT: ENC[AES256_GCM,data:ua2n3g==,iv:eXCXhqBMSJlB3E0NjrKhx1u+IogBVpz3lnB6+9IWavM=,tag:Xtd7cqjIgtrTPq+3/f1rOA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ETkpwhcd1lbuYPzUsLjUXrHRxEq2vPQ=,iv:9mwoCRqO6k3E9zLbKygGyI0BEEMNXgSia/HxKKM/Dqg=,tag:LtAfTP1gFwVF5SW1rEjahg==,type:str]
    PASSPORT_CLIENT_SECRET: ENC[AES256_GCM,data:OAVu8qIlSnBt/IEylgqvRzcllugYXmw7DA5LlQDhN16aW8qibNylDg==,iv:WSRsRpPeMY0CWorzP9x0CD0HKK4iRnNp81y9V/fE56k=,tag:pcg/Foeu5mpnrrITFenMtA==,type:str]
    REVENUE_CAT_SECRET_KEY: ENC[AES256_GCM,data:Iaoo3GxREd7YJPMETl4AEuHUAXx/uaUFlfxMkQS5i8c=,iv:qcuIDUyiofNd14R0Ll8BHwJQiGCmG+V0iOeY3fktbE8=,tag:R7j1BBIcRFJU3VR/YK4BDQ==,type:str]
    ADAPTY_SECRET_KEY: ENC[AES256_GCM,data:kYLJ+yJLx1eijjtAuubeDPydiky267rhTtvnfM2K9JRVqk7IEAPqrDJDLtBDRzzzZxHWq4k=,iv:D+dWyaQGI7/HFYl7eJa89fJlAhz+cf6GZpWPW4WG7zg=,tag:a048TbKfscCWp7RrABWaOQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:4yj/dRq2ko4ADpv/QPLJiggPbqL6Cgrk85X5S0ilY0p5YDu/HQtwOC2MmEOw89f1gG1j6k+XOiYqVAxla/LIvtd2XHRD4vjG3/jks0VFTVEwZRtIfWiOxuco,iv:2GEEaetlROzWsz9RmqGKw//wfFrydV+xqogcj+0kkrQ=,tag:kxUqnpiE3Psm0R1ctqySLA==,type:str]
    PUSHER_APP_KEY: ENC[AES256_GCM,data:2ToJMNTzHHP+aVe4B91bNF+9jB0bD8Wd6/u5jQEZswQx/syxY7EVwQ==,iv:n3ucpDE7EMOphIhwy6UEIVt6T5g2bRcEyzbGvJ1zY8A=,tag:L0zuSJOyoGRbgBXw6ffDBQ==,type:str]
    PUSHER_APP_SECRET: ENC[AES256_GCM,data:cN8e/Devvp2RpMMmktssOpm+WWs4lj1lTrNi6XfbzDoW8nFaRkh07w==,iv:fJ2r41O6amUEcjf10mbN900kGCF4MYo4dSr/jCxdfzk=,tag:q5ZxVG/+eHeDCUavQdwFkw==,type:str]
    MIX_PUSHER_APP_KEY: ENC[AES256_GCM,data:L8HIpjVpPcer7WlHwfn9ChYQ9yuLO52ADb2Tp8z4ZS7m9VOcY8NZJA==,iv:gaARJcXnSL0Ubdxiv9TWu7jvu4m6BO5odR6aqnMqoHE=,tag:dXGmOrpAfs9bQ0SdnbWHHg==,type:str]
    MIX_PUSHER_APP_CLUSTER: ENC[AES256_GCM,data:kbv9s1GC1JVPNC8bYQnsODUTisg6wXfT9IT1WMs8YYD8T6LEhOnGAg==,iv:WoQIWeRskacEvjXDV1Tg2cODMs0XkC7xFvMc/CREaQk=,tag:sTwmlYgJBIHcEEB1F3+V4A==,type:str]
    APN_PRIVATE_KEY: ENC[AES256_GCM,data:TeCFW0Ff9t3AF3cfChavfhBmcG+jrAS+BXgfU+YTrVQUJOKl+En0MaQPGFbCzgwAxcy3g6VJxfQ96P6QpXK8tGY7gAsiXAfKXyFbhJdxdgVfk4ioy+E20ZHKHjfs7RdpkCSiMBoro27OJ5n3dcFwZY+lQIst58Ak4dELucpdo3x8GeYq2y/4peoilGgR9AlSSDopdpAzP4CuIGO3J7QUY28z1Fb4Zt5kXrrajdEVmghV5bz7ykCkEsLkn3vcYwzgVyDCG+qi7V9IyD03n2y/TIbLt2o/p5DWOaPjwq4Du9h3mOhE22hle+HPUIWKE7Jj/TwCnts8kNlWRK1tJNfHwbo=,iv:BHtN9OD4MwzApddpowQmjqGXrR2RV7hEvSIHIisg4lo=,tag:IBuP4gXhnDl/BgTpKJoM4w==,type:str]
    SENTRY_LARAVEL_DSN: ENC[AES256_GCM,data:/1PFLahQKAKvMyvKWnac6MzSntXA40t8Sc4hVFk5kSd0t6t0qh5kcaJnU0un1eT6tuPgfhtD3sIexMy5Z8sL9O0=,iv:93KseUVOTmMLp3O70jNf6j6bGSit5EeqkviBGL1hsdg=,tag:0lP25AH5NZPwm/YCgTJAtg==,type:str]
    FLARE_KEY: ENC[AES256_GCM,data:rYceGR9oRmzvyrcqdS938tf7/NYYGfl4tyk8iQijKnf/4ema,iv:QhZFsq7/wW8WpJBMuOMrzOngh6+wIHVZhhfJSwqLZrI=,tag:yjmPQzgeqchDv7ynxYtbHg==,type:str]
    FACEBOOK_CLIENT_ID: ENC[AES256_GCM,data:ZaOZzqW9WmdGcSBszvNy,iv:Kz4OI10J85ZmyJPNIMr+nNY+UuWHoL56gJntYBJje2U=,tag:jMQaXsb/5DoQWX6bIR8bTA==,type:str]
    FACEBOOK_CLIENT_SECRET: ENC[AES256_GCM,data:lQE48DTFOsZoubYlCijeSS5E2Bhq/xm08GFF0DqcNZc=,iv:YvqweLAayMr3dmK0j0zpNB8d1k7H+kKSjOs9V8ARyZw=,tag:ke8ofoAoD1V+dnEZ+PSYNA==,type:str]
    APPLE_CLIENT_SECRET: ENC[AES256_GCM,data:uo3wndFvKz9Rk9hdk2LKWtz09Rhnnu2QEF6BmI8zm3gqcTTh8AvV7kz+fDii+dAzJUQ60+OeE0DIvo1eQFWEJb9WrV2wFluDzMiYBnRyxTD0NtccDu8FNQ8IEQrdpOnvZvkeO0yZQ7tVFGmFKL0cCQV0JNm0Q0Ga7mtEglMt0OO3fopDmQjybTBvMenZ+0wN6S8g+x5GNWr2adqX2vLPeLdbxP13isaB4lyhJJhWUmEe1THlHtJQzfNXFCucWjPyWcgor3LrVT9WX7dOMXfi3wmwuaWJjtaNOKyEoR5JKlQaE55l5SiDxTsTx5F2DJ6Gy5rCxoRXqbAnatWsDmLDF/mStUaFlKujmFqb/Pvwr/gb1L49fwU1a2qaEQPaVwAgHgE1Kk8kpbU9olnWQHHqVdcdyAQaLx803KeA5Eb9FhMMoA==,iv:hboN2eEfsHKDDPUWq/Si+rqMw5I/xfOyAXGSRjSb7EI=,tag:x2solSqOBLTu1z9LF7k6+w==,type:str]
    APPLE_PRIVATE_KEY: ENC[AES256_GCM,data:R2GEMGDJ+MjO7qTy3s/OWeZuKl/VgAVpH+bujj6o/AvEDeQOT/htR2ICFmJOLpk+M78JZ/3RrwJAwz60Pog0QkOoTTx9XNKKeLZwZiGgvI+oZH+jOXAhhRXtYfP1YbL3FCV4iFO8CC/7aNlhS8I+trjypeQs3ssV42m0MUGza238dqWNBsqxqvc1Mv+5ExzToTx5oKAw2XxPGYS0H9HORdtBsH8MPFR80m6cE42zZNuzRZl0Q3VSltuFViHnUcwzOTjzN6gfuc9sfjEkztcbfYDL2cBdUlC33EylQacSUEDCq879CXXKecZ5y56L6icYfjumgZqXQNRZvL4BaVC29Qg=,iv:VoJtveH5dCvaw5HpFUxkPPTHI4foPV2hD2z4Pa5CyWg=,tag:tda0OV16B11WpxO2FW2Cig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-18T02:42:37Z"
    mac: ENC[AES256_GCM,data:su+TGaJE/qmNTv9+6pu7PkpnPNAv1lJ+xA0jNtP4rNSLwNrO8U/Yyh4r7Dcr41D9ligkT7A2gUvDv01idI2T+eiVKavm7rouskVlreh4xq7odRaPcWPkbZ0WeD9uchlnj10yflba0x68ilylRMdZ/r7kioCl0Vj6+wVN/pydS5I=,iv:85FD3NdxDnHBGaVFrH5Yj+KA+xbqNN5rnCTugySBmpI=,tag:cECG9HppT2q480lTy5a9mw==,type:str]
    pgp:
        - created_at: "2022-05-18T02:42:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ/+P4opwv7otgNQX5rapFdgcJQDUz64QzuEBdXCyLlXcMfe
            V/kN57LNbWI5wAYmJSeS0N/KGop3xJkojeMG1lustpaiPR0DI7MGVINFhmSSwrBw
            LsCmLGLbWrmTpgUSBHgK/D06AaUkW4B2rJQtlsdzgJk++rvq90OEjFoRhPjBImwO
            PIt2CJ4D4ueWYaITwraMVmypr8joZGV0geAfIENMoEFc1hlj75hdFHEdkl3OZvME
            3cl4CoGyPnG1FBkR80xRyXLI8Kio9ZsA3bT4Gu3XHveV+TxqR9DZ1i790I8g+h0K
            m5kD7IcWsqUsvzXzWo4vSD5IxA91ZxFXN3QJwiBBXMUMOUk5O7lCn8yhNhSF89L7
            6R2keS1lFQX61nlzBc2aiK7HX4SyHSptrfDfiQXtRXtqOTEnmDA1onhKXZtNwkFX
            X2mK5IHXLDPrO1V1QQ4XpFVCo+X7I8+0UR6a/aKRrUWtMVbtttqXL2QH4lVMAQ4J
            qYNqJduJW5HBDwLfXEZHzxUmQQD6bAZEDm940mH4xR4cpl/LCIREYiS7uLOMwi4Z
            FTm1fY12W+1bDdbmdtM0RceyimpU259b4ehSn/GqORkoUJgFcRU7RunfF1L8osbs
            YtYqQM+0h4RVV8ybGZcHYsATKK+pFP1FtirL8facgr/a0zotADPwVAGKZ5l0rJXU
            ZgEJAhDyK3s+IZunpW8lPvRDABOz98Mdf/TjTKI9BZkxgSUmBMfhnGJtxHMiXUEc
            NwWpBqQBPd3IIf1f9wiPcxvTxUQRPo79RcN5ByGpJ1t8Xz6VIWRYQTA2UqS3djI7
            rX3YI5GPzQ==
            =hath
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
