---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
      chart: postgres-operator
      version: v1.8.1
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: flux-system
      interval: 5m
  values: { }
