---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 15m
  chart:
    spec:
      chart: k10
      version: 6.5.14
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    eula:
      accept: true
      company: nicko170
      email: nicko170@@users.noreply.github.com
    global:
      persistence:
        storageClass: rook-ceph-block
    auth:
      tokenAuth:
        enabled: true
    clusterName: k8s

    ingress:
      create: true
      class: nginx
      host: &domain "k10.${SECRET_CLUSTER_DOMAIN}"
      urlPath: k10
      hosts:
        - *domain
      tls:
        enabled: true
        secretName: *domain
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

    grafana:
      enabled: false
