---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-ui
  namespace: postgres
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
      chart: postgres-operator-ui
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui-charts
        namespace: flux-system
      interval: 5m
  values: { }
