---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postal-rabbitmq
  namespace: postal
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: rabbitmq
      version:
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      registry: docker.io
      repository: bitnami/rabbitmq
      tag: 4.0.2-debian-12-r2
      pullPolicy: IfNotPresent

    persistence:
      size: 2Gi

    auth:
      username: postal
      password: "${SECRET_POSTAL_RABBITMQ_PASS}"
      erlangCookie: "${SECRET_POSTAL_RABBITMQ_ERLANG}"

    extraConfiguration: |-
      default_vhost = postal
      default_permissions.configure = .*
      default_permissions.read = .*
      default_permissions.write = .*
