---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home.yaml
  - kasten-charts.yaml
  - metallb-charts.yaml
  - minio-charts.yaml
  - nicko170-charts.yaml
  - postgres-operator-charts.yaml
  - postgres-operator-ui-charts.yaml
  - rancher-charts.yaml
