---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator-ui-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  timeout: 3m
