---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: charts
  path: ./clusters/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
