apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLUSTER_EMAIL: ENC[AES256_GCM,data:yOycuexzcAYe2zm8JyPmCUg=,iv:YXhab3f/b7Kj0H6e45IDvKUGD1S1pEbAZhNbyILy9kY=,tag:+gPXyRNeJo8H8kwRG6Yy7w==,type:str]
    SECRET_CLUSTER_CF_EMAIL: ENC[AES256_GCM,data:oYgWy5dgiTYv0kORpSlBuOeM,iv:WesUbS9XTDhri61Fl7Ml7pMPqrIoiELh1sQShfmw72o=,tag:LA3MOtFjro4YRGC53MqsCg==,type:str]
    SECRET_CLUSTER_CF_API_KEY: ENC[AES256_GCM,data:Cu83zs8KushmtgwbSohnJ9fYjxvMn7GKB+k8Ui7B0bHbG66XXQ==,iv:pGa6CNEHa+SyKbdUG1p1qbOk++rpgVFH0Sa72ePq5Bc=,tag:mY3Dp4io9ECv/ozvE/WTjw==,type:str]
    SECRET_INGRESS_LB_IP: ENC[AES256_GCM,data:SeKoc722QQMZQhiQ,iv:Jed4nACINXLmqXn1s8SII9YVJKAlFKkwh4iMAN19wj8=,tag:cPxmd5viPC3hnOffE0/BGA==,type:str]
    SECRET_CLUSTER_DOMAIN: ENC[AES256_GCM,data:gC/3Wi8W1yP+5wE9,iv:YGX4ti1aHwCoqGjrdhu/n68POU5yEt5HhTPHLHxrYmg=,tag:J3R6QqMu5AA7wOU4nnogug==,type:str]
    SECRET_RANCHER_DOMAIN: ENC[AES256_GCM,data:qHgFe2ud0py8LVYXGezn9Z4=,iv:fFe2j1rf/1g4Z2XhwqqxXMYNMaSFq5Vv4Zq0u+29HCk=,tag:dxLW0PNkjma+vSY9pi94yQ==,type:str]
    SECRET_RFSPAGER_DB_PASSWORD: ENC[AES256_GCM,data:KsCE9IKb1uLxQz10RjWVCTh521EN9rU=,iv:GZ64El1OX9FU5b+47TRbhijwhU5KSk2a/iXtmwKngvg=,tag:cQA/PWg8GaP1j4dabSYVJw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:qw7OQcXPWjZrSoelM+ndnBeVUKpI3Ps=,iv:wDZJc5LMBqQ+sIIWc6oVyPQcDKGl/C0P7Kd6LkJ8Z3M=,tag:2xKgkEdIAokRvE/mXa8sYQ==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:t5Z3bHBrgJAXcxXw9aeP+lmO3taC9EyUeg0=,iv:pxL002DSwSSMPoWUwdFbYbpPtHU+HGfQcbclmUEI8hU=,tag:IA55wWgwiweh9/OHpjHmvw==,type:str]
    SECRET_MINIO_USER: ENC[AES256_GCM,data:nZ4lDww=,iv:Nb8GzvqgDPxGXacC2Rx6FSV5JpJ85lNjwbjR3k+ASKU=,tag:gwB1ZoDj/C0ygM3432wpZA==,type:str]
    SECRET_MINIO_PASS: ENC[AES256_GCM,data:PGxbn8LqLAlCMT22cC8tPpp+yY2bfwdy9w==,iv:+6WZJpOzwU/yJOzjmnlskWNRGpTOs/H2+FamPEtFq1U=,tag:XbRR/HMhLno8w5UDjXHd6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-21T07:39:11Z"
    mac: ENC[AES256_GCM,data:81gaEK8sARmF6JgQVL6sw/kyqO8t7jOo9xCvBTfPl5cenjsdyPD+HcsWvyJPsYY+ZhMjz+i/iRfz2LPGzykxwTuMGhT1/ttUj4yJoHYL1QVXxqXaiKBu348n8NmPqqTfOvZfBbIZ78m4X1IkeSWpzxxtH3tvYg2RF5uKXtG7qOM=,iv:ng1qhznnzM1bMLnGwIE2L0JEV3IbBDJfk0JSpaH8nYs=,tag:l2NbRN4tSAfazSkzXB6o4Q==,type:str]
    pgp:
        - created_at: "2022-05-21T07:39:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ/8DatFjQvDV/7jGNaHUNRjasI0zDSRXUZNnbkgWZiSpxdZ
            PnhHZCdCk4aSvh/tWQRCPF4tWNs8IKgyxeVLIcfa3KwLASxqZBQ8c3MILJN7p86f
            NloUajB2qgLv0zjMAekCj5q0veFVKpCaShIWjDXLpP1y1a8pXo9ywTmbST/TAsPe
            XeR5gNRE9EbZOG7o5+XDyHFLM/eIKqK80uM2etT9Thnk+/cqfXr6EGbh0/PWh/H8
            ttQX4cDz79MBdWBkkR0HEIUNalw50s3lwVxaBCm3qS5tn1Oj5gZj36poSFJpZU/q
            yZ8zFJ2qng8PHXGCwW44B8RJn9xt4qWzrleIHhUBFXEFtlCD7cQ5oLigYLsDqYEi
            WFTm4YrkiBMhXRxkKS/CpbPfESrXuxJAvlaBndZvW0mKLce01OoQd0SlY2zEP+aI
            jgujvrqiTIVbsAWwdXoKYLhtNw4WgnwFAMR6x0sTBVBdsMrSFVkXI0OveNk5bt1r
            p5zguipw9n7pPDphkklRkqdRH1DLLzDA+MxdDNqgsVKzhDmZspZvAKh6Xt2j7fUd
            EUCQU7w7bs8ieq5mkvV852z68yzTWuG4/wrCSdSyhWgDSQnbaZsCzQc58UBRuB7T
            UsXm24fgXDle1wlsZucKoDaI7j2EPx0SgmmW/wm1X+H9UpK0RuBHf+zQ+PDF46HU
            ZgEJAhAAooGPOs/+x7ZD2vls+BcTMiFzT3oMHZUI5PEjkMaa65fl2//gW/BAMAsM
            Se0qvanpH6Q4nzQApZc2UZ8RGHZX4PTkIDUO3PfJ2sBUbxxzzH0HtI9usvB6L8kH
            zHzmRb9UYQ==
            =Ybnp
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
