apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLUSTER_EMAIL: ENC[AES256_GCM,data:M7IfXhqjHTwyVKBntA5p/rE=,iv:4w6rVu1N6UN7uoxuwynQi3dJmjWcIPOHDNLHkZk1j14=,tag:PVLhR9EaGOFTYAofuCso8w==,type:str]
    SECRET_CLUSTER_CF_EMAIL: ENC[AES256_GCM,data:fgSizGNjt31JagS1dVWOmVKv,iv:5HPjavzUCvRHlbFMgFBWQQqyt5lJKJx6PEUVPEqB1cE=,tag:lb1W0vALfIC5k+iiWXjn7Q==,type:str]
    SECRET_CLUSTER_CF_API_KEY: ENC[AES256_GCM,data:jrWfStGg9umkQjwL+mbcpyGCQYrI7jvrCuhYTcvRz4nxOi/M9Q==,iv:VJ0nVUQ4rvDI9V5KhTl+RLfwydjjEoQfmAML50Ygvgo=,tag:5D4zgzi6JtpgYNVAgxZbfA==,type:str]
    SECRET_INGRESS_LB_IP: ENC[AES256_GCM,data:/FWPS4wfP7T4SYS1,iv:9tkC1tSeeZJKZ3SD2iiLl4fkEupEoUYe50h+UuI2wy8=,tag:cMKgNOe7BfblDIH6o1iByg==,type:str]
    SECRET_CLUSTER_DOMAIN: ENC[AES256_GCM,data:7vXxki/pgUWUpWeK,iv:piCDdKPp32Xf5GLkWbqMVVtvNlvx7oZ5Rk7QMmg28/o=,tag:XxW0QTt4g0b8hV3A0UvdFQ==,type:str]
    SECRET_RFSPAGER_DB_PASSWORD: ENC[AES256_GCM,data:u30zHlpMSciSgMOl/1Bg9asglfHEwEU=,iv:75i+IRBYO9AytIciKrGHI3ZvvQWx5JCleziI3i9uf1Q=,tag:biO7e1jj0hyb+BuqQlJ6dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-13T14:21:23Z"
    mac: ENC[AES256_GCM,data:CCaHBOahOYpTZRiW+28tuwcWkgtp+1h4//wSbfO5QZ3HIzoX72XJswZ8pk3bZyJEOYRqbOSXOPDu6Pr2gTWOeUojJhCtIYvEljAAn/DpxNHwOWE7Tna86JWvrgGERFHxzRO71uFP/mNlqOBFiC9TMgDLrOoZOmzjTmIRejuCJmw=,iv:ss0ytYefXUhOvwtxlVQsGQvvdYWjlPxd1x+SH1pzCTE=,tag:YIT2jZvHVvB81GYQzN6m+w==,type:str]
    pgp:
        - created_at: "2022-05-13T14:21:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94riJsaU78cAQ//Vl/xQpqYkdWwqgHh5YASWVESDlswJkUsxQCSVa7FRf+P
            aaOhSDPR0IWwrmHq7FC/UNHkesGEpUg/kDxGTbN2Ys3w+MVjlLLxd1ug8xkGOle4
            bKHaT9h1wU2H3ViJkGRPGilzrNqQ1f1dK6+ciepzqeOv9wYY6QKXpf2AA89Lg52s
            LzisQhRtYvX5CJpgjeOMzdbhD2tozzs9eMltwmpq5huisGlW/QIs0RcXlYtEeOa9
            2Y6xy+ZRHJCrOk9d0ARyQq0RgYFvR1bDoyWS00w1xKmHlVCQOcj90xr7AV3E0+IT
            jZ/EOh3JinuAJVdWhJthKgELMVCDDtJZCotfKTeSbjA9mWlKLUlyaSPUOCBB/VE4
            9NKMpBjOhsT9qSIQMK4l9uROEmmkjmJo1zYJIaWNOxf16yCGl9xPjGMPsp0/dAJ+
            5OToS6ZwWvZ52KtLzdezcsPFnfjQktyTx/mSneGqQ4PJrcjCVo5+0Gh94PJNY8Mr
            JKhgasGTH9j7e4Pqg0AR8R2o7EVAaRweC+SFwX7gqC5CJFurlAbaLPt6K4UksE7Y
            u+Zq4A/1sU/NO7t1NCHtRJUY5SfUyIuqRKmKPmpQksXukbcHHehuFrz9zHHswLjQ
            U3kamGR4afS7pQoQAwAIU6vMDB7PwFP3t0dD5I52Vd9RLCDya5N6BG/RB4TLLt/U
            aAEJAhB3RAxijbI6dsg+rhFdleM6MzHFmfl0ZLlxxgI+1ZZCIp9G/njPIaZRN1wO
            bMWnK30PHfJ/jlFJY+gxvGx/eb6S/0sWug3oZz5bj2aKp7x8RiOg7CgRBYbEojPw
            avSMZzE5L2SL
            =2xVP
            -----END PGP MESSAGE-----
          fp: B42C06716985941889E9BE3C3E7A0C9545A09F8C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
